{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3fe75c1e",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'pd' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "Input \u001b[0;32mIn [1]\u001b[0m, in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0m db \u001b[38;5;241m=\u001b[39m \u001b[43mpd\u001b[49m\u001b[38;5;241m.\u001b[39mread_csv(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mdb.csv\u001b[39m\u001b[38;5;124m'\u001b[39m)\n",
      "\u001b[0;31mNameError\u001b[0m: name 'pd' is not defined"
     ]
    }
   ],
   "source": [
    "db = pd.read_csv('db.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "71ee58fc",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "48972805",
   "metadata": {},
   "outputs": [],
   "source": [
    "db = pd.read_csv('db.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "ebd56675",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>id_slide</th>\n",
       "      <th>group</th>\n",
       "      <th>channel</th>\n",
       "      <th>position</th>\n",
       "      <th>template</th>\n",
       "      <th>title</th>\n",
       "      <th>data</th>\n",
       "      <th>filter</th>\n",
       "      <th>value1</th>\n",
       "      <th>value2</th>\n",
       "      <th>value3</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>s1111</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>CARTÕES</td>\n",
       "      <td>cartoes.csv</td>\n",
       "      <td>0</td>\n",
       "      <td>ACUMULADO</td>\n",
       "      <td>DIA</td>\n",
       "      <td>MM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>s1121</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>ACORDOS PF</td>\n",
       "      <td>acordospf.csv</td>\n",
       "      <td>0</td>\n",
       "      <td>ACUMULADO</td>\n",
       "      <td>DIA</td>\n",
       "      <td>MM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>s1131</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>CARTÕES PJ</td>\n",
       "      <td>cartoes.csv</td>\n",
       "      <td>0</td>\n",
       "      <td>ACUMULADO</td>\n",
       "      <td>DIA</td>\n",
       "      <td>MM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>s1141</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>ACORDOS PJ</td>\n",
       "      <td>acordospf.csv</td>\n",
       "      <td>0</td>\n",
       "      <td>ACUMULADO</td>\n",
       "      <td>DIA</td>\n",
       "      <td>MM</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>s1212</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>HUMANOS PRODUÇÃO</td>\n",
       "      <td>humanos_prod.csv</td>\n",
       "      <td>180</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>s1222</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>HUMANOS ACUMULADO</td>\n",
       "      <td>humanos_acum.csv</td>\n",
       "      <td>180</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>s1121</td>\n",
       "      <td>1</td>\n",
       "      <td>7</td>\n",
       "      <td>1</td>\n",
       "      <td>2</td>\n",
       "      <td>EFICIÊNCIA</td>\n",
       "      <td>eficiencia.csv</td>\n",
       "      <td>180</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>s1313</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>1</td>\n",
       "      <td>3</td>\n",
       "      <td>PRODUCÃO</td>\n",
       "      <td>producao.csv</td>\n",
       "      <td>180</td>\n",
       "      <td>TOTAL PREVENTIVOS</td>\n",
       "      <td>PARCIAIS</td>\n",
       "      <td>AVANCE</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>s1313</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>4</td>\n",
       "      <td>TAXA DE JUROS</td>\n",
       "      <td>taxa_juros.csv</td>\n",
       "      <td>180</td>\n",
       "      <td>JUROS (A.M.)</td>\n",
       "      <td>PARCIAIS</td>\n",
       "      <td>AVANCE</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  id_slide  group  channel  position  template              title  \\\n",
       "0    s1111      1        1         1         1            CARTÕES   \n",
       "1    s1121      1        1         2         1         ACORDOS PF   \n",
       "2    s1131      1        1         3         1         CARTÕES PJ   \n",
       "3    s1141      1        1         4         1         ACORDOS PJ   \n",
       "4    s1212      1        2         1         2   HUMANOS PRODUÇÃO   \n",
       "5    s1222      1        2         2         2  HUMANOS ACUMULADO   \n",
       "6    s1121      1        7         1         2         EFICIÊNCIA   \n",
       "7    s1313      1        3         1         3           PRODUCÃO   \n",
       "8    s1313      1        4         1         4      TAXA DE JUROS   \n",
       "\n",
       "               data  filter             value1    value2  value3  \n",
       "0       cartoes.csv       0          ACUMULADO       DIA      MM  \n",
       "1     acordospf.csv       0          ACUMULADO       DIA      MM  \n",
       "2       cartoes.csv       0          ACUMULADO       DIA      MM  \n",
       "3     acordospf.csv       0          ACUMULADO       DIA      MM  \n",
       "4  humanos_prod.csv     180                NaN       NaN     NaN  \n",
       "5  humanos_acum.csv     180                NaN       NaN     NaN  \n",
       "6    eficiencia.csv     180                NaN       NaN     NaN  \n",
       "7      producao.csv     180  TOTAL PREVENTIVOS  PARCIAIS  AVANCE  \n",
       "8    taxa_juros.csv     180       JUROS (A.M.)  PARCIAIS  AVANCE  "
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "db"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f9aa23a5",
   "metadata": {},
   "outputs": [],
   "source": [
    "db_aux = db.to_dict()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "601d174f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "{'group': {'s1111': 1,\n",
       "  's1121': 1,\n",
       "  's1131': 1,\n",
       "  's1141': 1,\n",
       "  's1212': 1,\n",
       "  's1222': 1,\n",
       "  's1313': 1},\n",
       " 'channel': {'s1111': 1,\n",
       "  's1121': 7,\n",
       "  's1131': 1,\n",
       "  's1141': 1,\n",
       "  's1212': 2,\n",
       "  's1222': 2,\n",
       "  's1313': 4},\n",
       " 'position': {'s1111': 1,\n",
       "  's1121': 1,\n",
       "  's1131': 3,\n",
       "  's1141': 4,\n",
       "  's1212': 1,\n",
       "  's1222': 2,\n",
       "  's1313': 1},\n",
       " 'template': {'s1111': 1,\n",
       "  's1121': 2,\n",
       "  's1131': 1,\n",
       "  's1141': 1,\n",
       "  's1212': 2,\n",
       "  's1222': 2,\n",
       "  's1313': 4},\n",
       " 'title': {'s1111': 'CARTÕES',\n",
       "  's1121': 'EFICIÊNCIA',\n",
       "  's1131': 'CARTÕES PJ',\n",
       "  's1141': 'ACORDOS PJ',\n",
       "  's1212': 'HUMANOS PRODUÇÃO',\n",
       "  's1222': 'HUMANOS ACUMULADO',\n",
       "  's1313': 'TAXA DE JUROS'},\n",
       " 'data': {'s1111': 'cartoes.csv',\n",
       "  's1121': 'eficiencia.csv',\n",
       "  's1131': 'cartoes.csv',\n",
       "  's1141': 'acordospf.csv',\n",
       "  's1212': 'humanos_prod.csv',\n",
       "  's1222': 'humanos_acum.csv',\n",
       "  's1313': 'taxa_juros.csv'},\n",
       " 'filter': {'s1111': 0,\n",
       "  's1121': 180,\n",
       "  's1131': 0,\n",
       "  's1141': 0,\n",
       "  's1212': 180,\n",
       "  's1222': 180,\n",
       "  's1313': 180},\n",
       " 'value1': {'s1111': 'ACUMULADO',\n",
       "  's1121': nan,\n",
       "  's1131': 'ACUMULADO',\n",
       "  's1141': 'ACUMULADO',\n",
       "  's1212': nan,\n",
       "  's1222': nan,\n",
       "  's1313': 'JUROS (A.M.)'},\n",
       " 'value2': {'s1111': 'DIA',\n",
       "  's1121': nan,\n",
       "  's1131': 'DIA',\n",
       "  's1141': 'DIA',\n",
       "  's1212': nan,\n",
       "  's1222': nan,\n",
       "  's1313': 'PARCIAIS'},\n",
       " 'value3': {'s1111': 'MM',\n",
       "  's1121': nan,\n",
       "  's1131': 'MM',\n",
       "  's1141': 'MM',\n",
       "  's1212': nan,\n",
       "  's1222': nan,\n",
       "  's1313': 'AVANCE'}}"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "db_aux"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "1da09182",
   "metadata": {},
   "outputs": [],
   "source": [
    "db = pd.read_csv('db.csv', index_col=0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ba32af73",
   "metadata": {},
   "outputs": [],
   "source": [
    "db_aux = db.to_dict"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
